services:
  rabbitmq:
    extends:
      file: docker-compose.base.yml
      service: rabbitmq

  db:
    extends:
      file: docker-compose.base.yml
      service: db
    image: ${DB_IMAGE_NAME:-cydeacode/cydeasoar_db}:v1

  app:
    extends:
      file: docker-compose.base.yml
      service: app
    image: ${APP_IMAGE_NAME:-cydeacode/cydeasoar_app}:v1

  worker:
    extends:
      file: docker-compose.base.yml
      service: worker
    image: ${APP_IMAGE_NAME:-cydeacode/cydeasoar_worker}:v1

  nginx:
    extends:
      file: docker-compose.base.yml
      service: nginx
    image: ${NGINX_IMAGE_NAME:-cydeacode/cydeasoar_nginx}:v1

volumes:
  iris-downloads:
  user_templates:
  server_data:
  db_data:

networks:
  iris_backend:
    name: iris_backend
  iris_frontend:
    name: iris_frontend
